# Generated by Django 3.2.5 on 2021-11-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invistame', '0007_auto_20211102_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='data',
        ),
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='hora',
            field=models.TimeField(default='11:21'),
        ),
    ]
