# Generated by Django 3.2.5 on 2021-11-03 23:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invistame', '0008_auto_20211103_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.TextField(max_length=200)),
                ('valor', models.FloatField(max_length=9)),
                ('pago', models.BooleanField(default=False)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default='19:26')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invistame.categoriagasto')),
            ],
        ),
        migrations.DeleteModel(
            name='Investimento',
        ),
    ]
