# Generated by Django 3.2.5 on 2021-11-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invistame', '0010_alter_gasto_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='hora',
            field=models.TimeField(default='19:38'),
        ),
    ]
